
def p(file_name,s):
     fp=open(file_name+".txt","a")
     fp.write(s+"\n\n\n")
    
     
def Bed(file_name):
    seq=["CASTING","PLANING","PLANING","STRESS","RELIEVING","PLANING","PLANO","MILLING","FITTING","INDUCTION","HARDENING-BEDS","SL.W.GRINDING","PLANING","PLANING","CNC","PLANO MILLING","R. DRILLING","FITTING","FETTLING","SL.W.GRINDING"];
    for i in seq:
        p(file_name,i)
                    
 


def Saddle(file_name):
    seq=["CASTING","MARKING","STRESS RELIEVING","PLANING","H. BORING & MILLING","FITTING","INDUCTION HARDENING-BEDS","SL.W. GRINDING","H. BORING & MILLING","PLANING","PLANING", "PLANING","PLANO MILLING","H. BORING & MILLING","V. BORING","PLANING","FETTLING","FITTING",	"DETAIL PAINTING","SL.W. GRINDING"];
    for i in seq:
        p(file_name,i)


def Crossslide(file_name):
    seq=["CASTING","MARKING","STRESS RELIEVING","PLANING","H. MILLING","PLANING","PLANING","H. MILLING","V. MILLING","H. BORING","H. BORING","V. BORING","R. DRILLING","H. MILLING","FETTLING","FITTING","DETAIL PAINTING"];
    for i in seq:
        p(file_name,i)



def Headstock(file_name):
    seq=["CASTING","MARKING","PLANO MILLING","H. BORING","STRESS RELIEVING","PLANO MILLING","PLANING","SCRAPING","MACHINING CENTRE","R.DRILLING","R. DRILLING","FETTLING","DETAIL PAINTING","HONING","FITTING"];
    for i in seq:
        p(file_name,i)




def Tailstock(file_name):
    seq=["CASTING","MARKING","V. MILLING","PLANING","H. MILLING","R. DRILLING","H. BORING","V. MILLING","PLANING","PLANING","SCRAPING","MACHINING CENTRE","FETTLING","FITTING","DETAIL PAINTING","HONING"];
    for i in seq:
        p(file_name,i)



def Cabinetleg(file_name):
    seq=["CASTING"];
    for i in seq:
        p(file_name,i)




def Endleg(file_name):
    seq=["CASTING","CNC PLANO MILLING","H. BORING","R. DRILLING","FITTING","DETAIL PAINTING"];
    for i in seq:
        p(file_name,i)



def Turrethousing(file_name):
    seq=["CASTING","MARKING","STRESS RELIEVING","PLANO MILLING","H. BORING","SCRAPING","MACHINING CENTRE","R. DRILLING","FITTING","DETAIL PAINTING","DETAIL PAINTING"];
    for i in seq:
        p(file_name,i)



def Turretdisc(file_name):
    seq=["CASTING","NORMALISING","TURNING - HEAVY DUTY","R. DRILLING","R. DRILLING","STRESS RELIEVING","SL.W. GRINDING","NC. TURNING","SL.W. GRINDING","MACHINING CENTRE","MACHINING CENTRE","R. DRILLING","FITTING","MACHINING CENTRE","FITTING","FITTING","MACHINING CENTRE","FITTING","MACHINING CENTRE","FITTING","BLACKENING"];
    for i in seq:
        p(file_name,i)



def Motorbase(file_name):
    seq=["CASTING","MARKING","PLANO MILLING","H. BORING & MILLING","R. DRILLING","FITTING","DETAIL PAINTING"];
    for i in seq:
        p(file_name,i)





def Motormountingplate(file_name):
    seq=["CASTING","T.WELDING: /GAS CUTTING","FETTLING","H. MILLING","FITTING","PLANING","VTC","FITTING","MARKING","R. DRILLING","R. DRILLING","BLACKENING"];
    for i in seq:
        p(file_name,i)




def TailstockBase(file_name):
    seq=["CASTING","MARKING","STRESS RELIEVING","PLANO MILLING","MARKING","R. DRILLING","H. BORING & MILLING","PLANING","H. BORING & MILLING","H. BORING","H. BORING","R. DRILLING","FITTING","DETAIL PAINTING"];
    for i in seq:
        p(file_name,i)




def MainSpindle(file_name):
    seq=["Forged& turned","NORMALISING","R. DRILLING","TURNING","D.H. BORING","TURNING","D.H. BORING","STRESS RELIEVING","STRESS RELIEVING","TURNING","NC. TURNING","NC. TURNING","INT. GRINDING","CARBURISING","TURNING","R. DRILLING","FITTING","HARDENING","SAND BLASTING","STRAIGHTENING","CYL. GRINDING","INT. GRINDING","CYL. GRINDING","K.W. MILLING","FITTING","STABLLISING","CYL. GRINDING","TURNING",
"INT. GRINDING","FITTING"];
    for i in seq:
        p(file_name,i)




def SPLINESHAFT(file_name):
    seq=["EN353","BAND SAW CUTTING","C. DRILLING","TURNING","SPLINE MILLING","FITTING","CARBURISING","SAND BLASTING","STRAIGHTENING","TURNING","TURNING","R. DRILLING","K.W. MILLING","FITTING","HARDENING","SAND BLASTING","STRAIGHTENING","K.W. MILLING","SPLINE GRINDING","CYL. GRINDING"];
    for i in seq:
        p(file_name,i)




def GEARSHAFT(file_name):
    seq=["EN353","BAND SAW CUTTING","R. DRILLING","NC. TURNING","TURNING","R. DRILLING","GEAR HOBBING","FITTING","SPLINE MILLING","FITTING","FITTING","CASE HARDENING","SAND BLASTING","STRAIGHTENING","FITTING","CENTRE GRINDING","CYL. GRINDING","TURNING","K.W.MILLING","FITTING","SPLINE GRINDING","GEAR GRINDING","GEAR GRINDING"];
    for i in seq:
        p(file_name,i)



def CYLINDER():
    seq=["EN8D","NORMALISING","NC. TURNING","STRESS RELIEVING","NC. TURNING","H. MILLING","FITTING","R. DRILLING","FITTING","CYL. GRINDING","CYL. GRINDING","INT. GRINDING"];
    return seq


def CYLINDERFLANGE(file_name):
    seq=["EN8D","NORMALISING","TURNING","TOUGHENING","NC. TURNING","H. MILLING","FITTING","R. DRILLING","MARKING","FITTING","FITTING","R.S.GRINDING","CYL. GRINDING","INT. GRINDING","JIG BORING","FITTING"];
    for i in seq:
        p(file_name,i)


def WORMSHAFT(file_name):
    seq=["EN353","BAND SAW CUTTING","C. DRILLING","TURNING","NC. TURNING","CARBURISING","TURNING","K.W. MILLING","FITTING","HARDENING","HARDENING","SAND BLASTING","CYL. GRINDING","THREAD GRINDING","ASSY"];
    for i in seq:
        p(file_name,i)




def TURRETSPINDLE(file_name):
    seq=["EN8D","CUTTING","R. DRILLING","NC. TURNING","TOUGHENING","NC. TURNING","TURNING","SPLINE MILLING","FITTING","CYL. GRINDING","CYL.GRINDING","SPLINE GRINDING","CYL. GRINDING","TURNING","R. DRILLING"];
    for i in seq:
        p(file_name,i)




def SHAFT(file_name):
    seq=["EN8D","BAND SAW CUTTING","TURNING","MARKING","R. DRILLING","V. MILLING","FITTING","CYL. GRINDING","BLACKENING"];
    for i in seq:
        p(file_name,i)




def TAILSTOCKSPINDLE(file_name):
    seq=["EN353"];
    for i in seq:
        p(file_name,i)



def SPURGEAR845030073C(file_name):
    seq=["EN353","NORMALISING","NC. TURNING","MARKING","R. DRILLING","GEAR HOBBING","GEAR TOOTH ROUNDING","FITTING","CARBURISING","TURNING","TURNING","V. BORING","FITTING","HARDENING","SAND BLASTING","INT. GRINDING","R.S. GRINDING","H. BROACHING","FITTING","INT. GRINDING","GEAR GRINDING"];
    for i in seq:
        p(file_name,i)



def SPURGEAR845030083D(file_name):
    seq=["EN353","CUTTING","TURNING","TURNING","GEAR HOBBING","GEAR TOOTH ROUNDING","FITTING","CASE HARDENING","SAND BLASTING","INT. GRINDING","INT. GRINDING","H. BROACHING","FITTING","INT. GRINDING","R.S. GRINDING","INT. GRINDING","GEAR GRINDING"];
    for i in seq:
        p(file_name,i)



def SPURGEAR845030093C(file_name):
    seq=["EN353","CUTTING","TURNING","TURNING","GEAR HOBBING","FITTING","CARBURISING","R. DRILLING","FITTING","HARDENING","HARDENING","SAND BLASTING","INT. GRINDING","H. BROACHING","FITTING","INT. GRINDING","GEAR GRINDING","GEAR GRINDING"];
    for i in seq:
        p(file_name,i)




def SPURGEAR845030233B(file_name):
    seq=["EN353","CUTTING","TURNING","GEAR SHAPING","GEAR TOOTH ROUNDING","FITTING","CARBURISING","TURNING","HARDENING","SAND BLASTING","SAND BLASTING","INT. GRINDING","R.S. GRINDING","CYL. GRINDING","SLOTTING","V. BROACHING","FITTING","TURNING","GEAR GRINDING","GEAR GRINDING","FITTING"];
    for i in seq:
        p(file_name,i)


def SPURGEAR845030243B(file_name):
    seq=["EN353","CUTTING","TURNING","GEAR HOBBING","GEAR TOOTH ROUNDING","FITTING","CARBURISING","TURNING","HARDENING","SAND BLASTING","SAND BLASTING","INT. GRINDING","CYL. GRINDING","SLOTTING","H. BROACHING","FITTING","TURNING","GEAR GRINDING","FITTING"];
    for i in seq:
        p(file_name,i)




def SPURGEAR845030253A(file_name):
    seq=["EN353","CUTTING","TURNING","GEAR HOBBING","FITTING","CARBURISING","TURNING","HARDENING","SAND BLASTING","INT. GRINDING","INT. GRINDING","SLOTTING","H. BROACHING","MARKING","R. DRILLING","FITTING","GEAR GRINDING","GEAR GRINDING","FITTING"];
    for i in seq:
        p(file_name,i)




def MATCHEDSETOFSPACER(file_name):
    seq=["EN8D","CUTTING","TURNING","MARKING","R. DRILLING","CUTTING","TURNING","R.S. GRINDING"];
    for i in seq:
        p(file_name,i)





def GEAR(file_name):
    seq=["CUTTING","TURNING","GEAR HOBBING","FITTING","CARBURISING","TURNING","R. DRILLING","FITTING","HARDENING","HARDENING","SAND BLASTING","INT. GRINDING","GEAR GRINDING","GEAR GRINDING"];
    for i in seq:
        p(file_name,i)





def WORMWHEEL(file_name):
    seq=["NC. TURNING","R. DRILLING","INT. GRINDING","THREAD GRINDING","GEAR HOBBING","FITTING"];
    for i in seq:
        p(file_name,i)




def TAPERLOCKBUSH_R(file_name):
    seq=["BAND SAW CUTTING","TURNING","TOUGHENING","CNC TURNING","V. BORING","FITTING","INT. GRINDING","CYL. GRINDING","MARKING","MARKING","H. MILLING","FITTING","BLACKENING"];
    for i in seq:
        p(file_name,i)




def TAPERLOCKBUSH_L(file_name):
    seq=["BAND SAW CUTTING","TURNING","TOUGHENING","CNC TURNING","V. BORING","FITTING","INT. GRINDING","CYL. GRINDING","MARKING","MARKING","H. MILLING","FITTING","BLACKENING"];
    for i in seq:
        p(file_name,i)






